SELECT B.HOUR, NVL(A.COUNT, 0) COUNT
FROM 
    (SELECT TO_CHAR(DATETIME, 'HH24') HOUR, COUNT(*) COUNT
        FROM ANIMAL_OUTS
        GROUP BY TO_CHAR(DATETIME, 'HH24')) A,
    (SELECT LEVEL - 1 AS HOUR FROM DUAL CONNECT BY LEVEL <= 24) B
WHERE A.HOUR(+) = B.HOUR
ORDER BY B.HOUR;